In [3]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\user\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.9.2                |   py37haa95532_0         2.9 MB
    ------------------------------------------------------------
                                           Total:         2.9 MB

The following packages will be UPDATED:

  conda                                        4.8.3-py37_0 --> 4.9.2-py37haa95532_0




conda-4.9.2          | 2.9 MB    |            |   0% 
conda-4.9.2          | 2.9 MB    | 1          |   1% 
conda-4.9.2          | 2.9 MB    | 2          |   3% 
conda-4.9.2          | 2.9 MB    | 5          |   6% 
conda-4.9.2          | 2.9 MB    | 8          |   8% 
conda-4.9.2          | 2.9 MB    | #          |  11% 
conda-4.9.2          | 2.9 MB    | #3         |  13% 
con

In [6]:
import numpy as np

In [7]:
np.__version__

'1.18.1'

In [8]:
a= np.array([1,2,3,5,7])

In [9]:
a

array([1, 2, 3, 5, 7])

In [10]:
type(a)

numpy.ndarray

In [1]:
%matplotlib inline

In [2]:
import matplotlib.pyplot as plt

In [3]:
import scipy.special as sps

In [1]:
import numpy as np

In [2]:
a =np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

In [3]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
b= np.flatten(a)

AttributeError: module 'numpy' has no attribute 'flatten'

In [7]:
b=a.ravel()

In [8]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
b[3]=300

In [10]:
b

array([  1,   2,   3, 300,   5,   6,   7,   8,   9,  10,  11,  12])

In [11]:
a

array([[  1,   2,   3, 300],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [12]:
a.ravel(order='C')

array([  1,   2,   3, 300,   5,   6,   7,   8,   9,  10,  11,  12])

In [13]:
a.ravel(order='F')

array([  1,   5,   9,   2,   6,  10,   3,   7,  11, 300,   8,  12])

In [14]:
a= np.arange(15)

In [15]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
a.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
a.reshape(4,3)

ValueError: cannot reshape array of size 15 into shape (4,3)

In [18]:
a.reshape(6,-1)

ValueError: cannot reshape array of size 15 into shape (6,newaxis)

In [19]:
a.reshape(5,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [20]:
b= a.reshape((3,-1))
b[1,3]=500
b

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 500,   9],
       [ 10,  11,  12,  13,  14]])

In [21]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7, 500,   9,  10,  11,  12,
        13,  14])

In [24]:
b= np.arange(20)

In [25]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:

b.resize((4,6),refcheck=False)
b


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19,  0,  0,  0,  0]])

In [28]:
c=np.arange(50)

In [29]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [30]:
c.resize((9,6),refcheck=False)

In [31]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49,  0,  0,  0,  0]])

In [32]:
c.shape

(9, 6)

In [33]:
c.sum(axis=0)

array([216, 225, 184, 192, 200, 208])

In [34]:
c.sum(axis=1)

array([ 15,  51,  87, 123, 159, 195, 231, 267,  97])

In [37]:
a=np.arange(24).reshape(6,4)

In [38]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
a.size

24

In [41]:
a.shape

(6, 4)

In [42]:
a[:,np.newaxis,:].shape

(6, 1, 4)

In [48]:
a=np.arange(6).reshape(3,2)

In [49]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [46]:
b=np.arange(8).reshape(4,2)

In [47]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [50]:
np.concatenate((a,b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [51]:
np.concatenate((b,a))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3],
       [4, 5]])

In [55]:
c=np.arange(6).reshape(3,2)
np.stack((a,c),axis=1)

array([[[0, 1],
        [0, 1]],

       [[2, 3],
        [2, 3]],

       [[4, 5],
        [4, 5]]])

In [56]:
np.hstack((a,c))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [1]:
np.vstack

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [4]:
a=np.arange(10).reshape(5,2)

In [5]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
np.split(a,5)

[array([[0, 1]]),
 array([[2, 3]]),
 array([[4, 5]]),
 array([[6, 7]]),
 array([[8, 9]])]

In [7]:
np.split(a,[3,2])

[array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([], shape=(0, 2), dtype=int32),
 array([[4, 5],
        [6, 7],
        [8, 9]])]

In [8]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [11]:
for i in a:
    print(i)

0
1
2
3
4


In [12]:
b=np.arange(8).reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
for j in b:
    print(j)

[0 1 2 3]
[4 5 6 7]


In [15]:
for i in b.flat:
    print(i)

0
1
2
3
4
5
6
7


In [17]:
a= np.random.rand(10)

In [18]:
a

array([0.94176894, 0.53426066, 0.67253392, 0.30476918, 0.61043771,
       0.33692847, 0.87745722, 0.95631841, 0.7844957 , 0.39292215])

In [19]:
np.amax(a)

0.9563184072502657

In [20]:
np.amin(a)

0.30476917914517654

In [23]:
np.amax(a, keepdims=True)

array([0.95631841])

In [24]:
np.amin(a, keepdims=True)

array([0.30476918])

In [26]:
a.max(axis=0)

0.9563184072502657

In [27]:
a.max(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [28]:
np.random.seed(0)

In [30]:
a=np.random.randint(1,20, size=(3,5))
a

array([[15, 17,  2,  9,  1],
       [ 5,  7, 14,  8, 16],
       [10, 19,  9, 16, 12]])

In [32]:
np.argmax(a)

11

In [33]:
np.argmax(a, axis=0)

array([0, 2, 1, 2, 1], dtype=int64)

In [34]:
np.argmax(a, axis=1)

array([1, 4, 1], dtype=int64)

In [36]:
a= np.random.randint(1,100, size=(3,5))
a

array([[39, 94,  2, 96, 45],
       [89, 25, 68, 83,  4],
       [77, 36, 87, 62, 70]])

In [37]:
np.where(a>60)

(array([0, 0, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([1, 3, 0, 2, 3, 0, 2, 3, 4], dtype=int64))

In [38]:
np.where(a>60,"Y","N")

array([['N', 'Y', 'N', 'Y', 'N'],
       ['Y', 'N', 'Y', 'Y', 'N'],
       ['Y', 'N', 'Y', 'Y', 'Y']], dtype='<U1')

In [41]:
np.random.seed(52)
k=np.random.randint(0,21,10)
k

array([11, 13,  0,  5, 10, 11,  3,  3,  1,  3])

In [42]:
np.nonzero(a)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [43]:
np.sort(a)

array([[ 2, 39, 45, 94, 96],
       [ 4, 25, 68, 83, 89],
       [36, 62, 70, 77, 87]])

In [44]:
np.argsort(a)

array([[2, 0, 4, 1, 3],
       [4, 1, 2, 3, 0],
       [1, 3, 4, 0, 2]], dtype=int64)

In [2]:
import numpy as np

In [4]:
np.add(1,2)

3

In [5]:
np.multiply(2,8)

16

In [6]:
np.divide(7,58)

0.1206896551724138

In [7]:
np.mod(45,5)

0

In [8]:
np.substract(a,b)

AttributeError: module 'numpy' has no attribute 'substract'

In [9]:
a=np.array([1,2,5,6,4])
b=np.array([3,2,3,4,23])

In [10]:
a+b

array([ 4,  4,  8, 10, 27])

In [11]:
np.add(a,b)

array([ 4,  4,  8, 10, 27])

In [12]:
a-b

array([ -2,   0,   2,   2, -19])

In [16]:
np.add(a,b)

array([ 4,  4,  8, 10, 27])

In [17]:
np.substract(a,b)

AttributeError: module 'numpy' has no attribute 'substract'

In [18]:
a/b

array([0.33333333, 1.        , 1.66666667, 1.5       , 0.17391304])

In [19]:
a*b

array([ 3,  4, 15, 24, 92])

In [20]:
a%b

array([1, 0, 2, 2, 4], dtype=int32)

In [21]:
c=np.arange(10)

In [22]:
a

array([1, 2, 5, 6, 4])

In [23]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
d=np.random.randint(1, 10, 20).reshape(2,10)

In [26]:
d

array([[4, 1, 1, 5, 5, 4, 9, 4, 2, 4],
       [4, 5, 5, 5, 8, 4, 8, 2, 7, 8]])

In [27]:
c*d

array([[ 0,  1,  2, 15, 20, 20, 54, 28, 16, 36],
       [ 0,  5, 10, 15, 32, 20, 48, 14, 56, 72]])

In [28]:
c+e


NameError: name 'e' is not defined

In [29]:
a=np.arange(10).reshape(2,5)

In [30]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
a.sum()

45

In [32]:
np.sum(a, axis=0)

array([ 5,  7,  9, 11, 13])

In [33]:
np.sum(a, axis=1)

array([10, 35])

In [34]:
2**3

8

In [35]:
np.power(2,3)

8

In [37]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [38]:
np.e

2.718281828459045

In [39]:
np.exp(1)

2.718281828459045

In [40]:
np.e

2.718281828459045

In [41]:
np.exp(np.arange(5))

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [43]:
np.log

<ufunc 'log'>

In [44]:
np.log2

<ufunc 'log2'>

In [45]:
import warnings

In [46]:
warnings.filterwarnings('ignore')

In [47]:
np.log([-1,1,2])

array([       nan, 0.        , 0.69314718])

In [48]:
p= np.array([1.65,1.55,-3.54, 2.05])
p

array([ 1.65,  1.55, -3.54,  2.05])

In [53]:
np.round(p, decimals=1)

array([ 1.6,  1.6, -3.5,  2. ])

In [60]:
np.rint(p)
# round 取最近的整數

array([ 2.,  2., -4.,  2.])

In [56]:
np.floor(p)
#向下取整數

array([ 1.,  1., -4.,  2.])

In [57]:
np.trunc(p)
#捨棄小數

array([ 1.,  1., -3.,  2.])

In [58]:
np.fix(p)
#向0取整數

array([ 1.,  1., -3.,  2.])

In [61]:
np.ceil(p)
#向上取整數

array([ 2.,  2., -3.,  3.])

In [62]:
np.abs(p)

array([1.65, 1.55, 3.54, 2.05])

In [65]:
np.absolute(p)

array([1.65, 1.55, 3.54, 2.05])

In [1]:
import numpy as np



In [3]:
np.random.seed(1)
a=np.random.randint(1,10,6).reshape(2,3)
b=np.random.randint(1,5,3)

In [5]:
a

array([[6, 9, 6],
       [1, 1, 2]])

In [6]:
b

array([1, 4, 2])

In [9]:
np.maximum(a,b)

array([[6, 9, 6],
       [1, 4, 2]])

In [10]:
np.minimum(a,b)

array([[1, 4, 2],
       [1, 1, 2]])

In [11]:
np.fmax(a,b)

array([[6, 9, 6],
       [1, 4, 2]])

In [13]:
np.nanmax([1,3,np.nan,10])

10.0

In [14]:
p=np.arange(1,20).astype('float32')
p

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.], dtype=float32)

In [15]:
np.percentile(p,[30,60])

array([ 6.4, 11.8])

In [16]:
a = np.array([23,  2,  1, np.nan,  9, 25, np.nan, 
              48, 43,  9, 31,  np.nan]).reshape(3, 4)

In [17]:
np.mean(a)

nan

In [20]:
a=np.arange(6).reshape((3,2))

In [21]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
np.average(a, axis=1,weights=[0.25,0.75])

array([0.75, 2.75, 4.75])

In [24]:
np.average(a, axis=1, weights=[0,0])

ZeroDivisionError: Weights sum to zero, can't be normalized

In [25]:
s=np.array([[1,2],[3,4]])

In [26]:
np.std(s)

1.118033988749895

In [27]:
np.var(a)

2.9166666666666665

In [28]:
np.var(a,axis=0)

array([2.66666667, 2.66666667])

In [29]:
np.var(a,axis=1)

array([0.25, 0.25, 0.25])

In [31]:
x=np.random.randint(1,20,10).reshape(2,5)

In [32]:
np.corrcoef(x)

array([[ 1.        , -0.48986688],
       [-0.48986688,  1.        ]])

In [33]:
np.correlate([1,2,3],[3,4])

array([11, 18])