In [3]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\user\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.9.2                |   py37haa95532_0         2.9 MB
    ------------------------------------------------------------
                                           Total:         2.9 MB

The following packages will be UPDATED:

  conda                                        4.8.3-py37_0 --> 4.9.2-py37haa95532_0




conda-4.9.2          | 2.9 MB    |            |   0% 
conda-4.9.2          | 2.9 MB    | 1          |   1% 
conda-4.9.2          | 2.9 MB    | 2          |   3% 
conda-4.9.2          | 2.9 MB    | 5          |   6% 
conda-4.9.2          | 2.9 MB    | 8          |   8% 
conda-4.9.2          | 2.9 MB    | #          |  11% 
conda-4.9.2          | 2.9 MB    | #3         |  13% 
con

In [6]:
import numpy as np

In [7]:
np.__version__

'1.18.1'

In [8]:
a= np.array([1,2,3,5,7])

In [9]:
a

array([1, 2, 3, 5, 7])

In [10]:
type(a)

numpy.ndarray

In [1]:
%matplotlib inline

In [2]:
import matplotlib.pyplot as plt

In [3]:
import scipy.special as sps

In [1]:
import numpy as np

In [2]:
a =np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

In [3]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
b= np.flatten(a)

AttributeError: module 'numpy' has no attribute 'flatten'

In [7]:
b=a.ravel()

In [8]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
b[3]=300

In [10]:
b

array([  1,   2,   3, 300,   5,   6,   7,   8,   9,  10,  11,  12])

In [11]:
a

array([[  1,   2,   3, 300],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [12]:
a.ravel(order='C')

array([  1,   2,   3, 300,   5,   6,   7,   8,   9,  10,  11,  12])

In [13]:
a.ravel(order='F')

array([  1,   5,   9,   2,   6,  10,   3,   7,  11, 300,   8,  12])

In [14]:
a= np.arange(15)

In [15]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
a.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
a.reshape(4,3)

ValueError: cannot reshape array of size 15 into shape (4,3)

In [18]:
a.reshape(6,-1)

ValueError: cannot reshape array of size 15 into shape (6,newaxis)

In [19]:
a.reshape(5,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [20]:
b= a.reshape((3,-1))
b[1,3]=500
b

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 500,   9],
       [ 10,  11,  12,  13,  14]])

In [21]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7, 500,   9,  10,  11,  12,
        13,  14])

In [24]:
b= np.arange(20)

In [25]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:

b.resize((4,6),refcheck=False)
b


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19,  0,  0,  0,  0]])

In [28]:
c=np.arange(50)

In [29]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [30]:
c.resize((9,6),refcheck=False)

In [31]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49,  0,  0,  0,  0]])

In [32]:
c.shape

(9, 6)

In [33]:
c.sum(axis=0)

array([216, 225, 184, 192, 200, 208])

In [34]:
c.sum(axis=1)

array([ 15,  51,  87, 123, 159, 195, 231, 267,  97])

In [37]:
a=np.arange(24).reshape(6,4)

In [38]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
a.size

24

In [41]:
a.shape

(6, 4)

In [42]:
a[:,np.newaxis,:].shape

(6, 1, 4)

In [48]:
a=np.arange(6).reshape(3,2)

In [49]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [46]:
b=np.arange(8).reshape(4,2)

In [47]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [50]:
np.concatenate((a,b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [51]:
np.concatenate((b,a))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3],
       [4, 5]])

In [55]:
c=np.arange(6).reshape(3,2)
np.stack((a,c),axis=1)

array([[[0, 1],
        [0, 1]],

       [[2, 3],
        [2, 3]],

       [[4, 5],
        [4, 5]]])

In [56]:
np.hstack((a,c))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [1]:
np.vstack

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [4]:
a=np.arange(10).reshape(5,2)

In [5]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
np.split(a,5)

[array([[0, 1]]),
 array([[2, 3]]),
 array([[4, 5]]),
 array([[6, 7]]),
 array([[8, 9]])]

In [7]:
np.split(a,[3,2])

[array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([], shape=(0, 2), dtype=int32),
 array([[4, 5],
        [6, 7],
        [8, 9]])]

In [8]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [11]:
for i in a:
    print(i)

0
1
2
3
4


In [12]:
b=np.arange(8).reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
for j in b:
    print(j)

[0 1 2 3]
[4 5 6 7]


In [15]:
for i in b.flat:
    print(i)

0
1
2
3
4
5
6
7


In [17]:
a= np.random.rand(10)

In [18]:
a

array([0.94176894, 0.53426066, 0.67253392, 0.30476918, 0.61043771,
       0.33692847, 0.87745722, 0.95631841, 0.7844957 , 0.39292215])

In [19]:
np.amax(a)

0.9563184072502657

In [20]:
np.amin(a)

0.30476917914517654

In [23]:
np.amax(a, keepdims=True)

array([0.95631841])

In [24]:
np.amin(a, keepdims=True)

array([0.30476918])

In [26]:
a.max(axis=0)

0.9563184072502657

In [27]:
a.max(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [28]:
np.random.seed(0)

In [30]:
a=np.random.randint(1,20, size=(3,5))
a

array([[15, 17,  2,  9,  1],
       [ 5,  7, 14,  8, 16],
       [10, 19,  9, 16, 12]])

In [32]:
np.argmax(a)

11

In [33]:
np.argmax(a, axis=0)

array([0, 2, 1, 2, 1], dtype=int64)

In [34]:
np.argmax(a, axis=1)

array([1, 4, 1], dtype=int64)

In [36]:
a= np.random.randint(1,100, size=(3,5))
a

array([[39, 94,  2, 96, 45],
       [89, 25, 68, 83,  4],
       [77, 36, 87, 62, 70]])

In [37]:
np.where(a>60)

(array([0, 0, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([1, 3, 0, 2, 3, 0, 2, 3, 4], dtype=int64))

In [38]:
np.where(a>60,"Y","N")

array([['N', 'Y', 'N', 'Y', 'N'],
       ['Y', 'N', 'Y', 'Y', 'N'],
       ['Y', 'N', 'Y', 'Y', 'Y']], dtype='<U1')

In [41]:
np.random.seed(52)
k=np.random.randint(0,21,10)
k

array([11, 13,  0,  5, 10, 11,  3,  3,  1,  3])

In [42]:
np.nonzero(a)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [43]:
np.sort(a)

array([[ 2, 39, 45, 94, 96],
       [ 4, 25, 68, 83, 89],
       [36, 62, 70, 77, 87]])

In [44]:
np.argsort(a)

array([[2, 0, 4, 1, 3],
       [4, 1, 2, 3, 0],
       [1, 3, 4, 0, 2]], dtype=int64)

In [2]:
import numpy as np

In [4]:
np.add(1,2)

3

In [5]:
np.multiply(2,8)

16

In [6]:
np.divide(7,58)

0.1206896551724138

In [7]:
np.mod(45,5)

0

In [8]:
np.substract(a,b)

AttributeError: module 'numpy' has no attribute 'substract'

In [9]:
a=np.array([1,2,5,6,4])
b=np.array([3,2,3,4,23])

In [10]:
a+b

array([ 4,  4,  8, 10, 27])

In [11]:
np.add(a,b)

array([ 4,  4,  8, 10, 27])

In [12]:
a-b

array([ -2,   0,   2,   2, -19])

In [16]:
np.add(a,b)

array([ 4,  4,  8, 10, 27])

In [17]:
np.substract(a,b)

AttributeError: module 'numpy' has no attribute 'substract'

In [18]:
a/b

array([0.33333333, 1.        , 1.66666667, 1.5       , 0.17391304])

In [19]:
a*b

array([ 3,  4, 15, 24, 92])

In [20]:
a%b

array([1, 0, 2, 2, 4], dtype=int32)

In [21]:
c=np.arange(10)

In [22]:
a

array([1, 2, 5, 6, 4])

In [23]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
d=np.random.randint(1, 10, 20).reshape(2,10)

In [26]:
d

array([[4, 1, 1, 5, 5, 4, 9, 4, 2, 4],
       [4, 5, 5, 5, 8, 4, 8, 2, 7, 8]])

In [27]:
c*d

array([[ 0,  1,  2, 15, 20, 20, 54, 28, 16, 36],
       [ 0,  5, 10, 15, 32, 20, 48, 14, 56, 72]])

In [28]:
c+e


NameError: name 'e' is not defined

In [29]:
a=np.arange(10).reshape(2,5)

In [30]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
a.sum()

45

In [32]:
np.sum(a, axis=0)

array([ 5,  7,  9, 11, 13])

In [33]:
np.sum(a, axis=1)

array([10, 35])

In [34]:
2**3

8

In [35]:
np.power(2,3)

8

In [37]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [38]:
np.e

2.718281828459045

In [39]:
np.exp(1)

2.718281828459045

In [40]:
np.e

2.718281828459045

In [41]:
np.exp(np.arange(5))

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [43]:
np.log

<ufunc 'log'>

In [44]:
np.log2

<ufunc 'log2'>

In [45]:
import warnings

In [46]:
warnings.filterwarnings('ignore')

In [47]:
np.log([-1,1,2])

array([       nan, 0.        , 0.69314718])

In [48]:
p= np.array([1.65,1.55,-3.54, 2.05])
p

array([ 1.65,  1.55, -3.54,  2.05])

In [53]:
np.round(p, decimals=1)

array([ 1.6,  1.6, -3.5,  2. ])

In [60]:
np.rint(p)
# round 取最近的整數

array([ 2.,  2., -4.,  2.])

In [56]:
np.floor(p)
#向下取整數

array([ 1.,  1., -4.,  2.])

In [57]:
np.trunc(p)
#捨棄小數

array([ 1.,  1., -3.,  2.])

In [58]:
np.fix(p)
#向0取整數

array([ 1.,  1., -3.,  2.])

In [61]:
np.ceil(p)
#向上取整數

array([ 2.,  2., -3.,  3.])

In [62]:
np.abs(p)

array([1.65, 1.55, 3.54, 2.05])

In [65]:
np.absolute(p)

array([1.65, 1.55, 3.54, 2.05])

In [1]:
import numpy as np



In [3]:
np.random.seed(1)
a=np.random.randint(1,10,6).reshape(2,3)
b=np.random.randint(1,5,3)

In [5]:
a

array([[6, 9, 6],
       [1, 1, 2]])

In [6]:
b

array([1, 4, 2])

In [9]:
np.maximum(a,b)

array([[6, 9, 6],
       [1, 4, 2]])

In [10]:
np.minimum(a,b)

array([[1, 4, 2],
       [1, 1, 2]])

In [11]:
np.fmax(a,b)

array([[6, 9, 6],
       [1, 4, 2]])

In [13]:
np.nanmax([1,3,np.nan,10])

10.0

In [14]:
p=np.arange(1,20).astype('float32')
p

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.], dtype=float32)

In [15]:
np.percentile(p,[30,60])

array([ 6.4, 11.8])

In [16]:
a = np.array([23,  2,  1, np.nan,  9, 25, np.nan, 
              48, 43,  9, 31,  np.nan]).reshape(3, 4)

In [17]:
np.mean(a)

nan

In [20]:
a=np.arange(6).reshape((3,2))

In [21]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
np.average(a, axis=1,weights=[0.25,0.75])

array([0.75, 2.75, 4.75])

In [24]:
np.average(a, axis=1, weights=[0,0])

ZeroDivisionError: Weights sum to zero, can't be normalized

In [25]:
s=np.array([[1,2],[3,4]])

In [26]:
np.std(s)

1.118033988749895

In [27]:
np.var(a)

2.9166666666666665

In [28]:
np.var(a,axis=0)

array([2.66666667, 2.66666667])

In [29]:
np.var(a,axis=1)

array([0.25, 0.25, 0.25])

In [31]:
x=np.random.randint(1,20,10).reshape(2,5)

In [32]:
np.corrcoef(x)

array([[ 1.        , -0.48986688],
       [-0.48986688,  1.        ]])

In [33]:
np.correlate([1,2,3],[3,4])

array([11, 18])

In [1]:
import numpy as np

In [2]:
with open('one_array.npy','wb') as f:
    np.save(f, np.array([1,2]))

In [3]:
np.load('one_array.npy')

array([1, 2])

In [6]:
with open('test.npy','wb')as f:
    np.save(f,np.array([1,2]))
    np.save(f, np.array([1,3]))
    np.save(f,np.array([1,4]))
    np.save(f,np.array([1,5]))

In [8]:
with open('test.npy','rb') as f:
    a = np.load(f)
    b = np.load(f)
    c = np.load(f)
    d = np.load(f)
print(a, b, c, d)

[1 2] [1 3] [1 4] [1 5]


In [14]:
x=np.arange(10)
y=np.array([1,2,3])
z=np.random.rand(10)

with open('wulti_array.npz','wb') as f:
    np.savez(f, array1=x, array2=y, array3=z)

In [17]:
npzfile=np.load('wulti_array.npz')

In [18]:
print(npzfile['array1'])
print(npzfile['array2'])
print(npzfile['array3'])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[0.46716188 0.59120234 0.92915901 0.2446007  0.86720506 0.4763863
 0.26306662 0.49808002 0.88974625 0.75944977]


In [25]:
x=y=z=np.arange(0.,5.,1.)

In [26]:
x

array([0., 1., 2., 3., 4.])

In [27]:
y=np.arange(10).reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
np.savetxt('test.out',x)

In [ ]:
# %load test.out
0.000000000000000000e+00
1.000000000000000000e+00
2.000000000000000000e+00
3.000000000000000000e+00
4.000000000000000000e+00


In [1]:
import numpy as np

In [2]:
np.random.seed(9)
a=np.random.randint(10, size=5)
b=np.random.randint(10, size=5)

In [3]:
a

array([5, 6, 8, 6, 1])

In [4]:
b

array([6, 4, 8, 1, 8])

In [5]:
np.inner(a,b)

132

In [6]:
np.outer(a,b)

array([[30, 20, 40,  5, 40],
       [36, 24, 48,  6, 48],
       [48, 32, 64,  8, 64],
       [36, 24, 48,  6, 48],
       [ 6,  4,  8,  1,  8]])

In [10]:
A=np.arange(6).reshape(2,3)
B=np.arange(12).reshape(3,4)

np.matmul(A,B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [11]:
A @B

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [14]:
np.transpose(A)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [17]:
B=np.array([[-2,-4,2],[-2,1,2],[4,2,5]])
B

array([[-2, -4,  2],
       [-2,  1,  2],
       [ 4,  2,  5]])

In [19]:
w, v= np.linalg.eig(B)

In [21]:
w #eigenvalues

array([-5.,  3.,  6.])

In [22]:
v #eogenbectors

array([[ 0.81649658,  0.53452248,  0.05842062],
       [ 0.40824829, -0.80178373,  0.35052374],
       [-0.40824829, -0.26726124,  0.93472998]])

In [23]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
a=np.array([[3,1],[1,2]])
b=np.array([9,8])
x=np.linalg.solve(a,b)
x

array([2., 3.])

In [27]:
np.eye(5,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [30]:
np.eye(3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [1]:
% load structured.txt

UsageError: Line magic function `%` not found.


In [2]:
import numpy as np

In [3]:
% load structured.txt

UsageError: Line magic function `%` not found.


In [4]:
dt=np.dtype('U5,i8,i8,U3')

In [6]:
a =np.genfromtxt('structured.txt',delimiter=',',dtype=dt)
a

OSError: structured.txt not found.

In [1]:
import pandas as pd

In [2]:
!pip install openpyxl
!pip install XLRD

In [3]:
iris_data=pd.read_csv('iris.csv')
iris_data

sepal length  sepal width  petal length  petal width  target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [4]:
iris_data=pd.read_csv('iris.csv',usecols=['petal length','petal width','target'])
iris_data

petal length  petal width  target
0             1.4          0.2       0
1             1.4          0.2       0
2             1.3          0.2       0
3             1.5          0.2       0
4             1.4          0.2       0
..            ...          ...     ...
145           5.2          2.3       2
146           5.0          1.9       2
147           5.2          2.0       2
148           5.4          2.3       2
149           5.1          1.8       2

[150 rows x 3 columns]

In [5]:
iris_data=pd.read_csv('iris.csv',header=0,names=['feature1','feature2','feature3','feature4','target'])
iris_data

feature1  feature2  feature3  feature4  target
0         5.1       3.5       1.4       0.2       0
1         4.9       3.0       1.4       0.2       0
2         4.7       3.2       1.3       0.2       0
3         4.6       3.1       1.5       0.2       0
4         5.0       3.6       1.4       0.2       0
..        ...       ...       ...       ...     ...
145       6.7       3.0       5.2       2.3       2
146       6.3       2.5       5.0       1.9       2
147       6.5       3.0       5.2       2.0       2
148       6.2       3.4       5.4       2.3       2
149       5.9       3.0       5.1       1.8       2

[150 rows x 5 columns]

In [6]:
iris_data.to_csv('my_iris.csv')

In [8]:
data=pd.read_excel('data.xls')
data

sepal length  sepal width  petal length  petal width  target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [9]:
boston_data=pd.read_excel('data.xls',sheet_name='boston')
boston_data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [10]:
boston_data=pd.read_excel('data.xls',sheet_name='boston',header=0 \
                         ,usecols=['TAX','PTRATIO','B','LSTAT'])
boston_data

TAX  PTRATIO       B  LSTAT
0    296     15.3  396.90   4.98
1    242     17.8  396.90   9.14
2    242     17.8  392.83   4.03
3    222     18.7  394.63   2.94
4    222     18.7  396.90   5.33
..   ...      ...     ...    ...
501  273     21.0  391.99   9.67
502  273     21.0  396.90   9.08
503  273     21.0  396.90   5.64
504  273     21.0  393.45   6.48
505  273     21.0  396.90   7.88

[506 rows x 4 columns]

In [15]:
boston_data.to_excel('my_boston.xlsx',sheet_name='boston')
boston_data[500:]

TAX  PTRATIO       B  LSTAT
500  391     19.2  396.90  14.33
501  273     21.0  391.99   9.67
502  273     21.0  396.90   9.08
503  273     21.0  396.90   5.64
504  273     21.0  393.45   6.48
505  273     21.0  396.90   7.88

In [16]:
import json

In [18]:
boston_data=pd.read_json('boston.json')
boston_data

TAX  PTRATIO       B  LSTAT
0    296     15.3  396.90   4.98
1    242     17.8  396.90   9.14
2    242     17.8  392.83   4.03
3    222     18.7  394.63   2.94
4    222     18.7  396.90   5.33
..   ...      ...     ...    ...
501  273     21.0  391.99   9.67
502  273     21.0  396.90   9.08
503  273     21.0  396.90   5.64
504  273     21.0  393.45   6.48
505  273     21.0  396.90   7.88

[506 rows x 4 columns]

In [19]:
boston_data.to_json('boston.json')

In [20]:
import sqlite3

In [26]:
boton_data=pd.read_excel('data.xls',sheet_name='boston',header=0 \
                        ,usecols=['TAX','PTRATIO','B','LSTAT'])
connection= sqlite3.connect('sql_db.sqlite')


In [28]:
boston_data.to_sql('boston', connection, if_exists='replace')
connection.commit()
connection.close()

In [29]:
connection=sqlite3.connect('sql_db.sqlite')
boston_data_sql=pd.io.sql.read_sql("select*from boston",connection)
connection.close()
boston_data_sql

index  TAX  PTRATIO       B  LSTAT
0        0  296     15.3  396.90   4.98
1        1  242     17.8  396.90   9.14
2        2  242     17.8  392.83   4.03
3        3  222     18.7  394.63   2.94
4        4  222     18.7  396.90   5.33
..     ...  ...      ...     ...    ...
501    501  273     21.0  391.99   9.67
502    502  273     21.0  396.90   9.08
503    503  273     21.0  396.90   5.64
504    504  273     21.0  393.45   6.48
505    505  273     21.0  396.90   7.88

[506 rows x 5 columns]

In [36]:
boston_data_sql


index  TAX  PTRATIO       B  LSTAT
0        0  296     15.3  396.90   4.98
1        1  242     17.8  396.90   9.14
2        2  242     17.8  392.83   4.03
3        3  222     18.7  394.63   2.94
4        4  222     18.7  396.90   5.33
..     ...  ...      ...     ...    ...
501    501  273     21.0  391.99   9.67
502    502  273     21.0  396.90   9.08
503    503  273     21.0  396.90   5.64
504    504  273     21.0  393.45   6.48
505    505  273     21.0  396.90   7.88

[506 rows x 5 columns]

In [1]:
import pandas as pd

In [3]:
boston_data=pd.read_csv('boston.csv',usecols=['CRIM','ZN','key','INDUS'])
boston_data_index = boston_data.set_index('key')
boston_data_index

ValueError: Usecols do not match columns, columns expected but not found: ['key']

In [5]:
import pandas as pd

In [39]:
boston_data=pd.read_csv('boston.csv',usecols=['CRIM','ZN','key','INDUS'])
boston_data_index=boston_data.set_index('key')
boston_data_index

CRIM   ZN  INDUS
key                     
1    0.02731  0.0   7.07
2    0.02729  0.0   7.07
3    0.03237  0.0   2.18
4    0.06905  0.0   2.18
5    0.02985  0.0   2.18
..       ...  ...    ...
501  0.06263  0.0  11.93
502  0.04527  0.0  11.93
503  0.06076  0.0  11.93
504  0.10959  0.0  11.93
505  0.04741  0.0  11.93

[505 rows x 3 columns]

In [9]:
boston_data_index.index

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            496, 497, 498, 499, 500, 501, 502, 503, 504, 505],
           dtype='int64', name='key', length=505)

In [10]:
boston_data_index2=boston_data.set_index(['key','INDUS'])
boston_data_index2

CRIM   ZN
key INDUS              
1   7.07   0.02731  0.0
2   7.07   0.02729  0.0
3   2.18   0.03237  0.0
4   2.18   0.06905  0.0
5   2.18   0.02985  0.0
...            ...  ...
501 11.93  0.06263  0.0
502 11.93  0.04527  0.0
503 11.93  0.06076  0.0
504 11.93  0.10959  0.0
505 11.93  0.04741  0.0

[505 rows x 2 columns]

In [11]:
boston_data_index2.index

MultiIndex([(  1,  7.07),
            (  2,  7.07),
            (  3,  2.18),
            (  4,  2.18),
            (  5,  2.18),
            (  6,  7.87),
            (  7,  7.87),
            (  8,  7.87),
            (  9,  7.87),
            ( 10,  7.87),
            ...
            (496,  9.69),
            (497,  9.69),
            (498,  9.69),
            (499,  9.69),
            (500,  9.69),
            (501, 11.93),
            (502, 11.93),
            (503, 11.93),
            (504, 11.93),
            (505, 11.93)],
           names=['key', 'INDUS'], length=505)

In [12]:
new_boston_data=boston_data.rename(columns={"CRIM":"feature1"})
new_boston_data

key  feature1   ZN  INDUS
0      1   0.02731  0.0   7.07
1      2   0.02729  0.0   7.07
2      3   0.03237  0.0   2.18
3      4   0.06905  0.0   2.18
4      5   0.02985  0.0   2.18
..   ...       ...  ...    ...
500  501   0.06263  0.0  11.93
501  502   0.04527  0.0  11.93
502  503   0.06076  0.0  11.93
503  504   0.10959  0.0  11.93
504  505   0.04741  0.0  11.93

[505 rows x 4 columns]

In [26]:
copy1=boston_data.copy()
copy1['round_INDUS']=round(copy1['INDUS'])
copy1

key     CRIM   ZN  INDUS  round_INDUS
0      1  0.02731  0.0   7.07          7.0
1      2  0.02729  0.0   7.07          7.0
2      3  0.03237  0.0   2.18          2.0
3      4  0.06905  0.0   2.18          2.0
4      5  0.02985  0.0   2.18          2.0
..   ...      ...  ...    ...          ...
500  501  0.06263  0.0  11.93         12.0
501  502  0.04527  0.0  11.93         12.0
502  503  0.06076  0.0  11.93         12.0
503  504  0.10959  0.0  11.93         12.0
504  505  0.04741  0.0  11.93         12.0

[505 rows x 5 columns]

In [21]:
copy2=boston_data.copy()
copy2.insert(3,'round_INDUS',round(copy2['INDUS']))
copy2

key     CRIM   ZN  round_INDUS  INDUS
0      1  0.02731  0.0          7.0   7.07
1      2  0.02729  0.0          7.0   7.07
2      3  0.03237  0.0          2.0   2.18
3      4  0.06905  0.0          2.0   2.18
4      5  0.02985  0.0          2.0   2.18
..   ...      ...  ...          ...    ...
500  501  0.06263  0.0         12.0  11.93
501  502  0.04527  0.0         12.0  11.93
502  503  0.06076  0.0         12.0  11.93
503  504  0.10959  0.0         12.0  11.93
504  505  0.04741  0.0         12.0  11.93

[505 rows x 5 columns]

In [22]:
del copy2['round_INDUS']
copy2

key     CRIM   ZN  INDUS
0      1  0.02731  0.0   7.07
1      2  0.02729  0.0   7.07
2      3  0.03237  0.0   2.18
3      4  0.06905  0.0   2.18
4      5  0.02985  0.0   2.18
..   ...      ...  ...    ...
500  501  0.06263  0.0  11.93
501  502  0.04527  0.0  11.93
502  503  0.06076  0.0  11.93
503  504  0.10959  0.0  11.93
504  505  0.04741  0.0  11.93

[505 rows x 4 columns]

In [27]:
print(copy1.pop('round_INDUS'))
copy1

0       7.0
1       7.0
2       2.0
3       2.0
4       2.0
       ... 
500    12.0
501    12.0
502    12.0
503    12.0
504    12.0
Name: round_INDUS, Length: 505, dtype: float64


key     CRIM   ZN  INDUS
0      1  0.02731  0.0   7.07
1      2  0.02729  0.0   7.07
2      3  0.03237  0.0   2.18
3      4  0.06905  0.0   2.18
4      5  0.02985  0.0   2.18
..   ...      ...  ...    ...
500  501  0.06263  0.0  11.93
501  502  0.04527  0.0  11.93
502  503  0.06076  0.0  11.93
503  504  0.10959  0.0  11.93
504  505  0.04741  0.0  11.93

[505 rows x 4 columns]

In [32]:
copy3=boston_data.copy()
copy3.drop('CRIM',axis=1)


key   ZN  INDUS
0      1  0.0   7.07
1      2  0.0   7.07
2      3  0.0   2.18
3      4  0.0   2.18
4      5  0.0   2.18
..   ...  ...    ...
500  501  0.0  11.93
501  502  0.0  11.93
502  503  0.0  11.93
503  504  0.0  11.93
504  505  0.0  11.93

[505 rows x 3 columns]

In [37]:
copy3=copy3.drop(1)
copy3

key     CRIM    ZN  INDUS
0      1  0.02731   0.0   7.07
2      3  0.03237   0.0   2.18
3      4  0.06905   0.0   2.18
4      5  0.02985   0.0   2.18
5      6  0.08829  12.5   7.87
..   ...      ...   ...    ...
500  501  0.06263   0.0  11.93
501  502  0.04527   0.0  11.93
502  503  0.06076   0.0  11.93
503  504  0.10959   0.0  11.93
504  505  0.04741   0.0  11.93

[504 rows x 4 columns]

In [49]:
copy3=copy3.append(pd.DataFrame([[506,0,1,2]],columns=boston_data.columns))
copy3

key     CRIM    ZN  INDUS
0      1  0.02731   0.0   7.07
2      3  0.03237   0.0   2.18
3      4  0.06905   0.0   2.18
4      5  0.02985   0.0   2.18
5      6  0.08829  12.5   7.87
..   ...      ...   ...    ...
503  504  0.10959   0.0  11.93
504  505  0.04741   0.0  11.93
0    506  0.00000   1.0   2.00
0    506  0.00000   1.0   2.00
0    506  0.00000   1.0   2.00

[507 rows x 4 columns]

In [51]:
stock_data=pd.read_csv('STOCK_DAY_0050_202010.csv')
stock_data[stock_data.open<105]

date    open    high     low   close
0   109/10/05  103.45  104.05  103.00  103.05
1   109/10/06  104.00  104.35  103.85  104.25
2   109/10/07  104.00  105.00  103.50  104.80
17  109/10/29  104.00  104.10  103.25  103.85
18  109/10/30  103.55  103.60  102.70  103.00

In [53]:
stock_data.loc[stock_data.open<105]

date    open    high     low   close
0   109/10/05  103.45  104.05  103.00  103.05
1   109/10/06  104.00  104.35  103.85  104.25
2   109/10/07  104.00  105.00  103.50  104.80
17  109/10/29  104.00  104.10  103.25  103.85
18  109/10/30  103.55  103.60  102.70  103.00

In [54]:
stock_data.loc[(stock_data.open<104)&(stock_data.close>100),['open','close']]

open   close
0   103.45  103.05
18  103.55  103.00

In [55]:
stock_data.iloc[3:10]

date    open    high     low   close
3  109/10/08  105.45  106.35  105.30  106.20
4  109/10/12  106.70  107.70  106.70  107.05
5  109/10/13  107.35  107.60  106.20  107.10
6  109/10/14  107.05  107.20  106.45  106.70
7  109/10/15  106.50  106.50  105.10  105.70
8  109/10/16  105.70  106.30  105.10  105.25
9  109/10/19  105.65  106.60  105.60  106.60

In [56]:
stock_data.iloc[:15,:3]

date    open    high
0   109/10/05  103.45  104.05
1   109/10/06  104.00  104.35
2   109/10/07  104.00  105.00
3   109/10/08  105.45  106.35
4   109/10/12  106.70  107.70
5   109/10/13  107.35  107.60
6   109/10/14  107.05  107.20
7   109/10/15  106.50  106.50
8   109/10/16  105.70  106.30
9   109/10/19  105.65  106.60
10  109/10/20  106.40  106.45
11  109/10/21  106.00  106.55
12  109/10/22  105.70  106.10
13  109/10/23  106.50  106.65
14  109/10/26  106.10  106.60

In [57]:
stock_data1=pd.read_csv('STOCK1.csv')
stock_data1

date    open   close
0  109/10/05  103.45  103.05
1  109/10/06  104.00  104.25
2  109/10/07  104.00  104.80
3  109/10/08  105.45  106.20
4  109/10/12  106.70  107.05
5  109/10/13  107.35  107.10

In [58]:
stock_data2=pd.read_csv('STOCK2.csv')
stock_data2

date    open    high
0  109/10/08  105.45  106.35
1  109/10/12  106.70  107.70
2  109/10/13  107.35  107.60
3  109/10/14  107.05  107.20
4  109/10/15  106.50  106.50

In [61]:
pd.concat([stock_data1,stock_data2],axis=1)

date    open   close       date    open    high
0  109/10/05  103.45  103.05  109/10/08  105.45  106.35
1  109/10/06  104.00  104.25  109/10/12  106.70  107.70
2  109/10/07  104.00  104.80  109/10/13  107.35  107.60
3  109/10/08  105.45  106.20  109/10/14  107.05  107.20
4  109/10/12  106.70  107.05  109/10/15  106.50  106.50
5  109/10/13  107.35  107.10        NaN     NaN     NaN

In [63]:
pd.concat([stock_data1,stock_data2],axis=0,join='inner')

date    open
0  109/10/05  103.45
1  109/10/06  104.00
2  109/10/07  104.00
3  109/10/08  105.45
4  109/10/12  106.70
5  109/10/13  107.35
0  109/10/08  105.45
1  109/10/12  106.70
2  109/10/13  107.35
3  109/10/14  107.05
4  109/10/15  106.50

In [64]:
pd.concat([stock_data1,stock_data2],axis=0,join='outer')

date    open   close    high
0  109/10/05  103.45  103.05     NaN
1  109/10/06  104.00  104.25     NaN
2  109/10/07  104.00  104.80     NaN
3  109/10/08  105.45  106.20     NaN
4  109/10/12  106.70  107.05     NaN
5  109/10/13  107.35  107.10     NaN
0  109/10/08  105.45     NaN  106.35
1  109/10/12  106.70     NaN  107.70
2  109/10/13  107.35     NaN  107.60
3  109/10/14  107.05     NaN  107.20
4  109/10/15  106.50     NaN  106.50

In [67]:
pd.merge(stock_data1,stock_data2,on='date',how='outer')

date  open_x   close  open_y    high
0  109/10/05  103.45  103.05     NaN     NaN
1  109/10/06  104.00  104.25     NaN     NaN
2  109/10/07  104.00  104.80     NaN     NaN
3  109/10/08  105.45  106.20  105.45  106.35
4  109/10/12  106.70  107.05  106.70  107.70
5  109/10/13  107.35  107.10  107.35  107.60
6  109/10/14     NaN     NaN  107.05  107.20
7  109/10/15     NaN     NaN  106.50  106.50

In [1]:
import pandas as pd

In [3]:
df= pd.DataFrame([['green','M','male','short'],
                ['red','L','female','normal'],
                ['blue','XL','male','long']])
df.columns=['color','size','sex','length']
df

color size     sex  length
0  green    M    male   short
1    red    L  female  normal
2   blue   XL    male    long

In [4]:
from sklearn.preprocessing import LabelEncoder
df['size_label']=LabelEncoder().fit_transform(df['size'].values)
df

color size     sex  length  size_label
0  green    M    male   short           1
1    red    L  female  normal           0
2   blue   XL    male    long           2

In [5]:
pf=pd.get_dummies(df[['color']])
pf=pd.concat([df,pf],axis=1)
pf

color size     sex  length  size_label  color_blue  color_green  color_red
0  green    M    male   short           1           0            1          0
1    red    L  female  normal           0           0            0          1
2   blue   XL    male    long           2           1            0          0

In [12]:
tenp_data = pd.DataFrame([['2020-11-01', 24.8],
                          ['2020-11-02', 24.8],
                          ['2020-11-03', None],
                          ['2020-11-04',25]],columns=['data','current_temp'])
tenp_data

data  current_temp
0  2020-11-01          24.8
1  2020-11-02          24.8
2  2020-11-03           NaN
3  2020-11-04          25.0

In [14]:
tenp_data.fillna(1)

data  current_temp
0  2020-11-01          24.8
1  2020-11-02          24.8
2  2020-11-03           1.0
3  2020-11-04          25.0

In [21]:
tenp_data.fillna(tenp_data.median())

data  current_temp
0  2020-11-01          24.8
1  2020-11-02          24.8
2  2020-11-03          24.8
3  2020-11-04          25.0

In [19]:
tenp_data.fillna(tenp_data.mean())

data  current_temp
0  2020-11-01     24.800000
1  2020-11-02     24.800000
2  2020-11-03     24.866667
3  2020-11-04     25.000000

In [23]:
tenp_data.fillna(method='bfill')

data  current_temp
0  2020-11-01          24.8
1  2020-11-02          24.8
2  2020-11-03          25.0
3  2020-11-04          25.0