In [2]:
import numpy as np

In [3]:
!pip install numpy

In [4]:
np.__version__

'1.18.1'

In [5]:
a =np.array([1,2,3,4,5])

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
b= np.array((5,6,7,8))

In [8]:

type(b)

numpy.ndarray

In [9]:
b

array([5, 6, 7, 8])

In [10]:
np.random.seed(1)

In [11]:
a=np.random.randint(1, 10, 6).reshape(2,3)

In [12]:
b=np.random.randint(1,5,3)

In [13]:
a

array([[6, 9, 6],
       [1, 1, 2]])

In [14]:


b

array([1, 4, 2])

In [15]:
np.maximum(a,b)

array([[6, 9, 6],
       [1, 4, 2]])

In [16]:
np.minimum(a,b)

array([[1, 4, 2],
       [1, 1, 2]])

In [17]:
np.maximum(a,[np.nan, 0, np.nan])

array([[nan,  9., nan],
       [nan,  1., nan]])

In [18]:
np.fmax(a, b)

array([[6, 9, 6],
       [1, 4, 2]])

In [19]:
np.fmin([np.nan, 3, np.nan],[np.nan, np.nan, np.nan])

array([nan,  3., nan])

In [20]:
np.nanmax([1, 2, np.nan, 3])

3.0

In [21]:
np.nan

nan

In [22]:
p=np.arange(1,20).astype('float32')
p

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.], dtype=float32)

In [23]:
np.percentile(p,[30,60])

array([ 6.4, 11.8])

In [24]:
p[5]=np.nan
p[14]=np.nan
p[12]=np.nan

In [25]:
p

array([ 1.,  2.,  3.,  4.,  5., nan,  7.,  8.,  9., 10., 11., 12., nan,
       14., nan, 16., 17., 18., 19.], dtype=float32)

In [26]:
np.nanpercentile(p, 50)

9.5

In [27]:
np.nanpercentile(p,34)

7.1000000000000005

In [28]:
np.percentile(p,10)

nan

In [29]:
np.percentile(p,20)

nan

In [30]:
q=np.array([32,43,25,32,21,4,24,3,6,3,5,32,56,35])
q

array([32, 43, 25, 32, 21,  4, 24,  3,  6,  3,  5, 32, 56, 35])

In [31]:
np.quantile(q,0.25)

5.25

In [37]:
a=np.array([23, 4, 2, np.nan, 9, 43, np.nan ,12 ,34 ,3 ,np.nan,4]).reshape(3,4)
a

array([[23.,  4.,  2., nan],
       [ 9., 43., nan, 12.],
       [34.,  3., nan,  4.]])

In [38]:
np.mean(a)

nan

In [39]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [43]:
np.average(a, axis=1, weights=[0.25, 0.75])

array([0.75, 2.75, 4.75])

In [44]:
np.average(a, axis=1, weights=[3,4])

array([0.57142857, 2.57142857, 4.57142857])

In [45]:
np.random.seed(5)
m=np.rando,.randint(1,50,15).reshape(3,5)

SyntaxError: invalid syntax (<ipython-input-45-28312aa3888e>, line 2)