作業目標

計算有缺失值的資料，統計量實作

作業重點

當遇到缺失值有函式可以處理，不須額外寫程式刪除
計算統計量時不能出現缺失值


題目:

english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,np.nan,60

chinese_score = np.array([65,90,82,72,66,77])

上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考
試，導致數學成績缺值，運用上列數據回答下列問題。

請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?

第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?

用補考後資料找出與國文成績相關係數最高的學科?

In [1]:
import numpy as np

請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?

In [5]:
english_mean=np.mean([55,89,76,65,48,70])
math_mean=np.nanmean([60,85,60,68,np.nan,60])
chinese_mean=np.mean([65,90,82,72,66,77])

In [6]:
english_mean

67.16666666666667

In [7]:
math_mean

66.6

In [8]:
chinese_mean

75.33333333333333

In [20]:
english_max=np.amax(english_score)
english_max

89

In [24]:
math_max=np.nanmax(math_score)
math_max

85.0

In [25]:
chinese_max=np.amax(chinese_score)
chinese_max

90

In [26]:
english_amin=np.amin(english_score)
english_score

array([55, 89, 76, 65, 48, 70])

In [29]:
math_min=np.nanmin(math_score)
math_min

60.0

In [30]:
chinese_min=np.nanmin(math_score)
chinese_min

60.0

In [33]:
english_std=np.std(english_score)
english_std

13.433995020924426

In [34]:
math_std=np.nanstd(math_score)
math_std

9.707728879609279

In [35]:
chinese_std=np.std(chinese_score)
chinese_std

8.825468196582484

第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?

In [36]:
math_score[4]=55

In [37]:
math55_mean=np.mean(math_score)
math55_mean

64.66666666666667

In [38]:
math55_max=np.amax(math_score)
math55_max

85.0

In [39]:
math55_min=np.amin(math_score)
math55_min

55.0

In [40]:
math55_std=np.std(math_score)
math55_std

9.860132971832694

用補考後資料找出與國文成績相關係數最高的學科?

In [42]:
np.corrcoef(english_score,chinese_score)

array([[1.        , 0.97792828],
       [0.97792828, 1.        ]])

In [43]:
np.corrcoef(math_score,chinese_score)

array([[1.        , 0.74056803],
       [0.74056803, 1.        ]])

數學成績是與國文成績相關係數最高的學科